server:
  port: ${dev.eureka.server.port}

eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8500/eureka/

spring:
  rabbitmq:
    host: 192.168.124.128
    port: 5672
    password: guest
    username: guest
    listener:
      simple:
        retry:
          enabled: false #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          max-attempts: 5 #最大重试次数
          initial-interval: 5000 #重试间隔时间（单位毫秒）
          max-interval: 1200000 #重试最大时间间隔（单位毫秒）
          multiplier: 5 #应用于前一重试间隔的乘法器
     fail-fast: true
